const fs = require("fs");
const p = "C:/Users/balai/Desktop/koenig-project/app/designs/4/page.tsx";
const L = [];
L.push("'use client'");
L.push("import { useState } from 'react'");
L.push("import Navbar from '@/components/Navbar'");
L.push("import Footer from '@/components/Footer'");
L.push("");
L.push("const courses = [");
L.push("  { name: 'Azure Solutions Architect Expert', vendor: 'Microsoft', price: '$1,495', days: 5, rating: 4.9, level: 'Expert', hot: true },");
L.push("  { name: 'AWS Solutions Architect – Associate', vendor: 'AWS', price: '$1,195', days: 4, rating: 4.8, level: 'Associate', hot: true },");
L.push("  { name: 'CCNP Enterprise Core', vendor: 'Cisco', price: '$1,295', days: 5, rating: 4.9, level: 'Professional', hot: false },");
L.push("  { name: 'CompTIA Security+', vendor: 'CompTIA', price: '$895', days: 5, rating: 4.7, level: 'Certification', hot: false },");
L.push("  { name: 'PMP', vendor: 'PMI', price: '$995', days: 3, rating: 4.8, level: 'Professional', hot: false },");
L.push("  { name: 'CEH v13', vendor: 'EC-Council', price: '$1,095', days: 5, rating: 4.8, level: 'Expert', hot: false },");
L.push("]");
L.push("");
L.push("const vendors = [");
L.push("  { name: 'Microsoft', tier: 'Gold Partner', initial: 'M', color: 'bg-blue-600', courses: '1,200+' },");
L.push("  { name: 'Cisco', tier: 'Premier Partner', initial: 'C', color: 'bg-blue-800', courses: '480+' },");
L.push("  { name: 'AWS', tier: 'Advanced Partner', initial: 'A', color: 'bg-orange-500', courses: '320+' },");
L.push("  { name: 'VMware', tier: 'Principal Partner', initial: 'V', color: 'bg-green-700', courses: '180+' },");
L.push("  { name: 'Oracle', tier: 'Gold Partner', initial: 'O', color: 'bg-red-700', courses: '290+' },");
L.push("  { name: 'CompTIA', tier: 'Platinum Partner', initial: 'C', color: 'bg-red-500', courses: '150+' },");
L.push("  { name: 'PMI', tier: 'Authorized Partner', initial: 'P', color: 'bg-purple-700', courses: '85+' },");
L.push("  { name: 'ISC2', tier: 'Official Partner', initial: 'I', color: 'bg-teal-700', courses: '60+' },");
L.push("  { name: 'SAP', tier: 'Gold Partner', initial: 'S', color: 'bg-blue-900', courses: '130+' },");
L.push("  { name: 'Google Cloud', tier: 'Premier Partner', initial: 'G', color: 'bg-green-600', courses: '200+' },");
L.push("  { name: 'Salesforce', tier: 'Silver Partner', initial: 'S', color: 'bg-sky-500', courses: '110+' },");
L.push("  { name: 'Red Hat', tier: 'Advanced Partner', initial: 'R', color: 'bg-red-600', courses: '95+' },");
L.push("]");
L.push("");
L.push("const formats = [");
L.push("  { icon: '🏛️', name: 'Classroom Training', desc: 'In-person at 13+ countries', features: ['Hands-on labs', 'Face-to-face instruction', 'On-site exam booking'], from: '$1,295', cta: 'Book Classroom' },");
L.push("  { icon: '💻', name: 'Live Online', desc: 'Real-time, all timezones', features: ['Live instructor', 'Interactive Q&A', 'Global access'], from: '$895', cta: 'Join Online', badge: 'Best Value' },");
L.push("  { icon: '⚡', name: 'FMAT', desc: 'Fast-Track, 2–5x faster', features: ['Your own dates', 'Custom pace', '1-on-1 attention'], from: '$1,695', cta: 'Choose FMAT', badge: 'Fastest' },");
L.push("  { icon: '📱', name: 'Flexi Training', desc: 'Self-paced, 1-on-1 format', features: ['90-day access', 'Practice exams', 'Anytime, anywhere'], from: '$395', cta: 'Start Now' },");
L.push("]");
L.push("");
L.push("const differentiators = [");
L.push("  { icon: '🎯', title: 'Outcomes, Not Just Completion', desc: '95% first-attempt pass rate across all programs. Our training is designed to get you certified, not just to fill seats.' },");
L.push("  { icon: '👤', title: '1-on-1 Instructor Attention', desc: '300+ certified trainers dedicated to individual students — not batch lectures with 30 people sharing one instructor.' },");
L.push("  { icon: '📅', title: 'Schedules That Never Cancel', desc: '99.1% on-time delivery rate. Book your travel with confidence — we have never cancelled a committed batch in 30 years.' },");
L.push("  { icon: '💰', title: 'Money-Back Guarantee', desc: '100% satisfaction guarantee on every course. Not satisfied? We make it right — no questions, no hassle, no hidden clauses.' },");
L.push("]");
fs.writeFileSync(p, L.join(String.fromCharCode(10)), "utf8");
console.log("Part1 written, lines:", L.length);