export type Webinar = {
  id: number
  speaker: string
  initials: string
  photo: string
  avatarBg: string
  title: string
  description: string
  partner: string
  technology: string
  date: string
  time: string
  duration: string
  registered: number
  live: boolean
}

/* ── Webinar data ───────────────────────────────────────────── */
export const WEBINARS: Webinar[] = [
  {
    id: 1,
    speaker: 'Nidhi Karthik Nayak',
    initials: 'NK',
    photo: 'https://rms.koenig-solutions.com/Sync_data/AutoResume/imagePhoto/08_Jun_2026_14_29_22_704Nidhi.jpg',
    avatarBg: 'linear-gradient(135deg,#34A853,#076D9D)',
    title: 'Work Smarter With Microsoft 365 Copilot',
    description: 'Discover how AI can simplify daily tasks, boost productivity, and unlock creativity across Word, Excel, PowerPoint, Outlook, and Teams—with practical Copilot use cases for everyday work.',
    partner: 'Microsoft',
    technology: 'Microsoft',
    date: '06 Jul 2026',
    time: '01:00 PM IST',
    duration: '1 Hour',
    registered: 45,
    live: true,
  },
  {
    id: 2,
    speaker: 'Lipika Sharma',
    initials: 'LS',
    photo: 'https://rms.koenig-solutions.com/Sync_data/Files/EmpPhoto/2024123594-Pic2.jpg',
    avatarBg: 'linear-gradient(135deg,#EC4899,#8B5CF6)',
    title: 'Microsoft AI Certification Fundamentals Series: AI 900 To AI Engineer Roadmap',
    description: 'Explore the complete Microsoft AI certification path from AI-900 fundamentals to the full AI Engineer roadmap, with exam preparation strategies and real-world AI application scenarios.',
    partner: 'Microsoft',
    technology: 'AI',
    date: '29 Jun 2026',
    time: '05:00 PM IST',
    duration: '1 Hour',
    registered: 79,
    live: false,
  },
  {
    id: 3,
    speaker: 'Rashmi Sharma',
    initials: 'RS',
    photo: 'https://rms.koenig-solutions.com/Sync_data/AutoResume/imagePhoto/Rashmi%20Sharma.png',
    avatarBg: 'linear-gradient(135deg,#0694D1,#38bdf8)',
    title: 'DP-603: Implement Real Time Analytics With Microsoft Fabric',
    description: 'Learn to implement real-time analytics using Microsoft Fabric. Covers DP-603 exam topics including data streaming, pipelines, and building intelligent analytics solutions at scale.',
    partner: 'Microsoft',
    technology: 'Data',
    date: '29 Jun 2026',
    time: '06:00 PM IST',
    duration: '1 Hour',
    registered: 38,
    live: false,
  },
  {
    id: 4,
    speaker: 'Bharat Singh Thakur',
    initials: 'BT',
    photo: 'https://rms.koenig-solutions.com/Sync_data/AutoResume/imagePhoto/19_Jan_2026_11_6_28_38WhatsApp%20Image%202026-01-14%20at%209.44.47%20AM.jpeg',
    avatarBg: 'linear-gradient(135deg,#F59E0B,#B45309)',
    title: 'Mastering SAP LAM & The S/4HANA 9 Phase Maintenance Model',
    description: 'Deep dive into SAP Linear Asset Management and the structured 9-phase maintenance model in S/4HANA for enterprise-grade asset lifecycle management and operational efficiency.',
    partner: 'SAP',
    technology: 'ERP',
    date: '06 Jul 2026',
    time: '05:00 PM IST',
    duration: '1 Hour',
    registered: 12,
    live: false,
  },
  {
    id: 5,
    speaker: 'K M Bilvika',
    initials: 'KB',
    photo: 'https://rms.koenig-solutions.com/Sync_data/AutoResume/imagePhoto/11_Nov_2022_9_59_15_824BV%20Photo.jpg',
    avatarBg: 'linear-gradient(135deg,#065F46,#10B981)',
    title: 'PostgreSQL Database Administration',
    description: 'Master PostgreSQL DBA essentials—installation, configuration, backup & recovery, performance tuning, high availability, and security best practices for production environments.',
    partner: 'PostgreSQL',
    technology: 'Database',
    date: '06 Jul 2026',
    time: '06:00 PM IST',
    duration: '1 Hour',
    registered: 8,
    live: false,
  },
  {
    id: 6,
    speaker: 'Vinod Kumar',
    initials: 'VK',
    photo: 'https://rms.koenig-solutions.com/Sync_data/AutoResume/imagePhoto/31_Oct_2019_9_51_10_591vinodkumar.jpg',
    avatarBg: 'linear-gradient(135deg,#1D4ED8,#3B82F6)',
    title: 'Workflow Management Using Java And Spring Boot',
    description: 'Learn to design and implement enterprise-grade workflow management systems using Java and Spring Boot, covering state machines, process automation, and RESTful API patterns.',
    partner: 'Java',
    technology: 'Development',
    date: '06 Jul 2026',
    time: '06:00 PM IST',
    duration: '1 Hour',
    registered: 22,
    live: false,
  },
  {
    id: 7,
    speaker: 'Akash Rai',
    initials: 'AR',
    photo: 'https://rms.koenig-solutions.com/Sync_data/AutoResume/imagePhoto/12_Mar_2026_8_45_44_158my%20pic.jpg',
    avatarBg: 'linear-gradient(135deg,#DC2626,#F97316)',
    title: 'AI Driven Generative Design And Smart Manufacturing With Fusion 360',
    description: 'Explore how AI and generative design in Autodesk Fusion 360 are revolutionizing smart manufacturing—from concept generation to production-ready designs and simulation.',
    partner: 'Autodesk',
    technology: 'AI',
    date: '06 Jul 2026',
    time: '07:00 PM IST',
    duration: '1 Hour',
    registered: 5,
    live: false,
  },
  {
    id: 8,
    speaker: 'Sachin Chauhan',
    initials: 'SC',
    photo: 'https://rms.koenig-solutions.com/Sync_data/AutoResume/imagePhoto/Sachin%20Chauhan.png',
    avatarBg: 'linear-gradient(135deg,#0694D1,#7c3aed)',
    title: 'Designing Microsoft AI Agents With Copilot Studio – From Idea To Impact',
    description: 'Build intelligent AI agents with Microsoft Copilot Studio—from initial concept to enterprise deployment—covering agent design, actions, connectors, and real-world integration patterns.',
    partner: 'Microsoft',
    technology: 'AI',
    date: '06 Jul 2026',
    time: '08:00 PM IST',
    duration: '1 Hour',
    registered: 31,
    live: false,
  },
  {
    id: 9,
    speaker: 'Anshu Jayant Batra',
    initials: 'AB',
    photo: 'https://rms.koenig-solutions.com/Sync_data/AutoResume/imagePhoto/Anshu%20Jayant%20Batra.png',
    avatarBg: 'linear-gradient(135deg,#0694D1,#076D9D)',
    title: 'Automating Legacy Systems And Desktop Applications Using Microsoft Power Automate',
    description: 'Discover how Microsoft Power Automate desktop flows can modernize and automate legacy systems without costly rewrites, enabling seamless integration and end-to-end process automation.',
    partner: 'Microsoft',
    technology: 'Microsoft',
    date: '07 Jul 2026',
    time: '01:00 PM IST',
    duration: '1 Hour',
    registered: 19,
    live: false,
  },
  {
    id: 10,
    speaker: 'Jasleen Kaur',
    initials: 'JK',
    photo: 'https://rms.koenig-solutions.com/Sync_data/AutoResume/imagePhoto/19_Dec_2025_7_25_2_926pp2025.jpg',
    avatarBg: 'linear-gradient(135deg,#7c3aed,#a78bfa)',
    title: 'DP-700 Exam Prep In 1 Hour',
    description: 'Fast-track your DP-700 Microsoft Fabric Analytics Engineer certification with a focused 1-hour review of exam objectives, key concepts, practice patterns, and time-saving strategies.',
    partner: 'Microsoft',
    technology: 'Data',
    date: '07 Jul 2026',
    time: '03:00 PM IST',
    duration: '1 Hour',
    registered: 14,
    live: false,
  },
  {
    id: 11,
    speaker: 'Bharat Singh Thakur',
    initials: 'BT',
    photo: 'https://rms.koenig-solutions.com/Sync_data/AutoResume/imagePhoto/19_Jan_2026_11_6_28_38WhatsApp%20Image%202026-01-14%20at%209.44.47%20AM.jpeg',
    avatarBg: 'linear-gradient(135deg,#F59E0B,#B45309)',
    title: 'Transitioning From SAP GUI To SAP Fiori Applications',
    description: 'Navigate the shift from SAP GUI to the modern SAP Fiori UX—covering migration strategies, Fiori app design principles, Launchpad configuration, and deployment best practices.',
    partner: 'SAP',
    technology: 'ERP',
    date: '07 Jul 2026',
    time: '04:00 PM IST',
    duration: '1 Hour',
    registered: 7,
    live: false,
  },
  {
    id: 12,
    speaker: 'Sajiyabanu Salat',
    initials: 'SS',
    photo: 'https://rms.koenig-solutions.com/Sync_data/AutoResume/imagePhoto/10_Nov_2025_20_24_26_537WhatsApp%20Image%202025-09-18%20at%2010.02.25%20PM.jpeg',
    avatarBg: 'linear-gradient(135deg,#F47920,#f6a05c)',
    title: 'GitHub Is More Than Push And Pull: Features Every Developer Should Know',
    description: 'Unlock the full potential of GitHub beyond basic version control—explore Actions, Codespaces, Copilot, Projects, and security scanning features every modern developer should leverage.',
    partner: 'GitHub',
    technology: 'DevOps',
    date: '07 Jul 2026',
    time: '05:00 PM IST',
    duration: '1 Hour',
    registered: 16,
    live: false,
  },
  {
    id: 13,
    speaker: 'Vinod Kumar',
    initials: 'VK',
    photo: 'https://rms.koenig-solutions.com/Sync_data/AutoResume/imagePhoto/31_Oct_2019_9_51_10_591vinodkumar.jpg',
    avatarBg: 'linear-gradient(135deg,#1D4ED8,#3B82F6)',
    title: 'Oracle WebLogic Administration Basics',
    description: 'Get started with Oracle WebLogic Server administration—covering domain configuration, application deployment, clustering, monitoring, security configuration, and troubleshooting fundamentals.',
    partner: 'Oracle',
    technology: 'Database',
    date: '07 Jul 2026',
    time: '06:00 PM IST',
    duration: '1 Hour',
    registered: 3,
    live: false,
  },
  {
    id: 14,
    speaker: 'Priya Nair',
    initials: 'PN',
    photo: 'https://rms.koenig-solutions.com/Sync_data/AutoResume/imagePhoto/Priya%20Nair.png',
    avatarBg: 'linear-gradient(135deg,#BE185D,#F472B6)',
    title: 'AWS Solutions Architect: Key Concepts & Exam Strategy',
    description: 'Master the core AWS architectural principles and exam strategies for the Solutions Architect Associate certification, with hands-on pattern walkthroughs and practice questions.',
    partner: 'AWS',
    technology: 'Cloud',
    date: '08 Jul 2026',
    time: '01:00 PM IST',
    duration: '1 Hour',
    registered: 42,
    live: false,
  },
  {
    id: 15,
    speaker: 'Rahul Verma',
    initials: 'RV',
    photo: 'https://rms.koenig-solutions.com/Sync_data/AutoResume/imagePhoto/Rahul%20Verma.png',
    avatarBg: 'linear-gradient(135deg,#0369A1,#38BDF8)',
    title: 'Zero Trust Security: Principles & Implementation',
    description: 'Understand the Zero Trust architecture model and learn practical implementation steps for identity, device, network, and data security in modern enterprise environments.',
    partner: 'PECB',
    technology: 'Security',
    date: '08 Jul 2026',
    time: '02:00 PM IST',
    duration: '1 Hour',
    registered: 28,
    live: false,
  },
  {
    id: 16,
    speaker: 'Anita Desai',
    initials: 'AD',
    photo: 'https://rms.koenig-solutions.com/Sync_data/AutoResume/imagePhoto/Anita%20Desai.png',
    avatarBg: 'linear-gradient(135deg,#7C3AED,#C4B5FD)',
    title: 'Power BI: From Data to Actionable Insights',
    description: 'Learn to transform raw data into compelling dashboards using Power BI—covering data modelling, DAX fundamentals, visual best practices, and publishing to Power BI Service.',
    partner: 'Microsoft',
    technology: 'Data',
    date: '08 Jul 2026',
    time: '03:00 PM IST',
    duration: '1 Hour',
    registered: 61,
    live: false,
  },
  {
    id: 17,
    speaker: 'Suresh Pillai',
    initials: 'SP',
    photo: 'https://rms.koenig-solutions.com/Sync_data/AutoResume/imagePhoto/Suresh%20Pillai.png',
    avatarBg: 'linear-gradient(135deg,#D97706,#FCD34D)',
    title: 'Kubernetes for Developers: Containers at Scale',
    description: 'Get hands-on with Kubernetes fundamentals—pods, services, deployments, config maps, and scaling strategies—designed for developers building and deploying containerised applications.',
    partner: 'Linux',
    technology: 'DevOps',
    date: '08 Jul 2026',
    time: '04:00 PM IST',
    duration: '1 Hour',
    registered: 33,
    live: false,
  },
  {
    id: 18,
    speaker: 'Meera Krishnan',
    initials: 'MK',
    photo: 'https://rms.koenig-solutions.com/Sync_data/AutoResume/imagePhoto/Meera%20Krishnan.png',
    avatarBg: 'linear-gradient(135deg,#047857,#34D399)',
    title: 'ITIL 4 Foundation: Service Management Essentials',
    description: 'A focused overview of ITIL 4 Foundation concepts—service value system, four dimensions model, guiding principles, and key practices to prepare for your certification exam.',
    partner: 'PECB',
    technology: 'IT Service',
    date: '09 Jul 2026',
    time: '01:00 PM IST',
    duration: '1 Hour',
    registered: 24,
    live: false,
  },
  {
    id: 19,
    speaker: 'Deepak Joshi',
    initials: 'DJ',
    photo: 'https://rms.koenig-solutions.com/Sync_data/AutoResume/imagePhoto/Deepak%20Joshi.png',
    avatarBg: 'linear-gradient(135deg,#1E40AF,#60A5FA)',
    title: 'Azure DevOps: CI/CD Pipelines from Scratch',
    description: 'Build robust CI/CD pipelines in Azure DevOps from scratch—covering repos, build pipelines, release management, artefact feeds, and integration with GitHub and container registries.',
    partner: 'Microsoft',
    technology: 'DevOps',
    date: '09 Jul 2026',
    time: '02:00 PM IST',
    duration: '1 Hour',
    registered: 47,
    live: false,
  },
  {
    id: 20,
    speaker: 'Kavitha Rajan',
    initials: 'KR',
    photo: 'https://rms.koenig-solutions.com/Sync_data/AutoResume/imagePhoto/Kavitha%20Rajan.png',
    avatarBg: 'linear-gradient(135deg,#9D174D,#F9A8D4)',
    title: 'Ethical Hacking & Penetration Testing Fundamentals',
    description: 'Learn the core methodologies of ethical hacking and penetration testing—reconnaissance, scanning, exploitation, and reporting—using industry-standard tools and frameworks.',
    partner: 'PECB',
    technology: 'Security',
    date: '09 Jul 2026',
    time: '03:00 PM IST',
    duration: '1 Hour',
    registered: 55,
    live: false,
  },
  {
    id: 21,
    speaker: 'Arjun Menon',
    initials: 'AM',
    photo: 'https://rms.koenig-solutions.com/Sync_data/AutoResume/imagePhoto/Arjun%20Menon.png',
    avatarBg: 'linear-gradient(135deg,#0F766E,#5EEAD4)',
    title: 'Google Cloud Professional: Data Engineer Exam Guide',
    description: 'Prepare for the Google Cloud Professional Data Engineer exam with a structured walkthrough of BigQuery, Dataflow, Pub/Sub, and ML model deployment on GCP.',
    partner: 'Google',
    technology: 'Cloud',
    date: '09 Jul 2026',
    time: '04:00 PM IST',
    duration: '1 Hour',
    registered: 18,
    live: false,
  },
  {
    id: 22,
    speaker: 'Sonal Mehta',
    initials: 'SM',
    photo: 'https://rms.koenig-solutions.com/Sync_data/AutoResume/imagePhoto/Sonal%20Mehta.png',
    avatarBg: 'linear-gradient(135deg,#92400E,#F59E0B)',
    title: 'Project Management Professional (PMP): Exam Prep Sprint',
    description: 'An intensive 1-hour sprint covering the latest PMP exam domains—people, process, and business environment—with mnemonics, practice tips, and the most-tested concepts.',
    partner: 'PMI',
    technology: 'Management',
    date: '10 Jul 2026',
    time: '01:00 PM IST',
    duration: '1 Hour',
    registered: 36,
    live: false,
  },
]

/* ── Partner logos ───────────────────────────────────────────── */
export const PARTNER_LOGOS: Record<string, string> = {
  'Microsoft': '/images/partners/microsoft-cloud-t.png',
  'SAP':       '/images/partners/SAP.jpg',
  'PECB':      '/images/partners/Authorized PECB Certification Courses Training badge.png',
  'Autodesk':  '/images/partners/AutodeskCertification.png',
}

/* ── Related courses (by webinar technology) ─────────────────── */
export type RelatedCourse = { code: string; title: string; url: string }

export const RELATED_COURSES: Record<string, RelatedCourse[]> = {
  Microsoft: [
    { code: 'AZ-104T00', title: 'Microsoft Azure Administrator', url: 'https://www.koenig-solutions.com/microsoft-azure-administrator-training' },
    { code: 'AB-731T00', title: 'Drive AI transformation in your organization', url: 'https://www.koenig-solutions.com/ai-course-google' },
    { code: 'PL-100', title: 'Microsoft Copilot Studio – Build AI-Powered Chatbots', url: 'https://www.koenig-solutions.com/microsoft-ai-training' },
  ],
  AI: [
    { code: 'AB-731T00', title: 'Drive AI transformation in your organization', url: 'https://www.koenig-solutions.com/ai-course-google' },
    { code: 'AI-900', title: 'Introduction to AI in Azure', url: 'https://www.koenig-solutions.com/ai-900-certification-cost' },
    { code: 'AI-102', title: 'Azure AI Engineer Associate Certification', url: 'https://www.koenig-solutions.com/azure-ai-certification' },
  ],
  Data: [
    { code: 'DP-600T00', title: 'Microsoft Fabric Analytics Engineer', url: 'https://www.koenig-solutions.com/data-analytics-online-training' },
    { code: 'DP-900', title: 'Microsoft Azure Data Fundamentals', url: 'https://www.koenig-solutions.com/microsoft-azure-fundamentals-training' },
    { code: 'PL-300', title: 'Power BI: From Data to Actionable Insights', url: 'https://www.koenig-solutions.com/power-bi-training' },
  ],
  ERP: [
    { code: 'S4H00', title: 'SAP S/4HANA Fundamentals', url: 'https://www.koenig-solutions.com/sap-s4hana-training' },
    { code: 'UX400', title: 'SAP Fiori Application Development', url: 'https://www.koenig-solutions.com/sap-fiori-training' },
    { code: 'PLM230', title: 'SAP Linear Asset Management (LAM)', url: 'https://www.koenig-solutions.com/sap-plm-training' },
  ],
  Database: [
    { code: 'PG-DBA', title: 'PostgreSQL Database Administration', url: 'https://www.koenig-solutions.com/postgresql-training' },
    { code: 'OCP-DBA', title: 'Oracle Database Administration', url: 'https://www.koenig-solutions.com/oracle-database-administration-training' },
    { code: 'DP-3020', title: 'Develop Data-Driven Applications with Azure SQL Database', url: 'https://www.koenig-solutions.com/sql-certification-course' },
  ],
  Development: [
    { code: 'JAVA-SB', title: 'Workflow Management Using Java and Spring Boot', url: 'https://www.koenig-solutions.com/java-spring-boot-training' },
    { code: 'AZ-204T00', title: 'Developing Solutions for Microsoft Azure', url: 'https://www.koenig-solutions.com/developing-solutions-microsoft-azure-training' },
    { code: 'GH-100', title: 'GitHub Fundamentals for Developers', url: 'https://www.koenig-solutions.com/github-training-online' },
  ],
  DevOps: [
    { code: 'CKA', title: 'Certified Kubernetes Administrator (CKA)', url: 'https://www.koenig-solutions.com/kubernetes-training' },
    { code: 'AZ-400T00', title: 'Designing and Implementing Microsoft DevOps Solutions', url: 'https://www.koenig-solutions.com/az-400-devops-solutions-training' },
    { code: 'GH-200', title: 'Automate Your Workflow with GitHub Actions', url: 'https://www.koenig-solutions.com/github-actions-certification' },
  ],
  Cloud: [
    { code: 'SAP-C02', title: 'AWS Certified Solutions Architect – Professional', url: 'https://www.koenig-solutions.com/aws-solutions-architect-training' },
    { code: 'GPDE', title: 'Google Cloud Professional Data Engineer', url: 'https://www.koenig-solutions.com/google-cloud-data-engineer-training' },
    { code: 'AZ-900T00-A', title: 'Introduction to Microsoft Azure', url: 'https://www.koenig-solutions.com/microsoft-azure-fundamentals-training' },
  ],
  Security: [
    { code: 'CEH-P', title: 'Certified Ethical Hacker (CEH) – Practical', url: 'https://www.koenig-solutions.com/ceh-certification-training' },
    { code: 'SY0-701', title: 'CompTIA Security+', url: 'https://www.koenig-solutions.com/comptia-security-plus-training' },
    { code: 'ZT-100', title: 'Zero Trust Security: Principles & Implementation', url: 'https://www.koenig-solutions.com/zero-trust-security-training' },
  ],
  'IT Service': [
    { code: 'ITIL-4F', title: 'ITIL 4 Foundation Certification', url: 'https://www.koenig-solutions.com/itil-4-foundation-training' },
    { code: 'ITIL-4SL', title: 'ITIL 4 Specialist: Create, Deliver and Support', url: 'https://www.koenig-solutions.com/itil-4-specialist-training' },
    { code: 'VeriSM', title: 'VeriSM Foundation', url: 'https://www.koenig-solutions.com/verism-foundation-training' },
  ],
  Management: [
    { code: 'PMP', title: 'Project Management Professional (PMP)', url: 'https://www.koenig-solutions.com/pmp-certification-training' },
    { code: 'CAPM', title: 'Certified Associate in Project Management (CAPM)', url: 'https://www.koenig-solutions.com/capm-certification-training' },
    { code: 'PRINCE2', title: 'PRINCE2 Foundation and Practitioner', url: 'https://www.koenig-solutions.com/prince2-certification-training' },
  ],
}
